#!/usr/bin/env node

const fs = require('fs');

const fileName = './failed_test_specs.log'
const outputFileName = './e2e_test_specs.log';

const prepareE2ETestSpecs = () => {
    fs.readFile(fileName, {encoding: 'utf8'}, function(err,data){
        if (!err) {
            writeFile('./' + outputFileName, data); 
        } else {
            writeFile('./' + outputFileName, 'cypress/e2e/*.spec.js'); 
        }
    });
}

async function writeFile(fileName, content) { 
    await fs.promises.writeFile(fileName, content); 
}

prepareE2ETestSpecs();

