#!/usr/bin/env node

const fs = require('fs');

const fileName = process.argv[2][0];
const content = process.argv[2][1];

const writeFiles = () => {
    fs.writeFile('./cypress/logs/' + fileName, content); 
}

writeFiles();

